POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "name4",
  "category": "category",
  "price": 10.00,
  "availabilityDate": "2022-12-29",
  "description": "description",
  "discontinued": false,
  "images": "images",
  "scheduledMaps": "maps",
  "scheduledPrices": "prices",
  "scheduledSales": "sales",
  "shipmentCost": "cost"
}

###
