
PUT http://localhost:8080/shipment/2
Content-Type: application/json

{
  "productId": 70,
  "quantity": 20,
  "cost": 99.50
}

###

PUT http://localhost:8080/category/1
Content-Type: application/json

{
  "name": "updated category name"
}
###

